# syntax highlighting
"attribute" = "yellow"
"type" = "yellow"
"constructor" = "blue"
"constant" = "yellow"
"constant.character.escape" = "cyan"
"string"  = "green"
"comment" = { fg = "gray", modifiers = ["italic"] }
"variable" = "white"
"variable.builtin" = "red"
"variable.parameter" = "red"
"variable.other.member" = "cyan"
"label" = "magenta"
"keyword" = "magenta"
"function" = "blue"
"namespace" = "magenta"
"special" = "blue"
"markup.heading" = "magenta"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.label" = { fg = "blue" }
"markup.quote" = "cyan"
"markup.raw" = "green"
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "yellow"

# interface
"ui.cursor" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "yellow", modifiers = ["bold"] }
"ui.cursor.primary" = { fg = "white", modifiers = ["reversed"] }
"ui.debug" = "gray"
"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }
"ui.popup" = { bg = "black" }
"ui.window" = { bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.virtual.ruler" = { bg = "black" }
"ui.virtual.whitespace" = "white"
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.selection" = { fg = "gray", modifiers = ["reversed"] }
"diagnostic" = { modifiers = ["underlined"] }
"hint" = "gray"
"info" = "blue"
"warning" = "yellow"
"error" = "red"
