[[language]]
name = "go"
formatter = { command = "goimports" }

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.json.path=stdout", "--show-stats=false", "--issues-exit-code=1", "--enable=gosec"]
